### ISSUE TITLE
Missing and misplaced learning language flags

### ISSUE THREAD

**Issue by jimmysoda** [mofman/DuolingoCourseSwitcher#5]
All but one of the learning language flags per "from" language is missing. The remaining flag corresponds to the last learning language and is misplaced to the top of the list. I reproduced this issue with both Greasemonkey on Firefox v46.0.1 and Tampermonkey on Chrome v51.0.2704.103 with English, Spanish, and Portuguese as the "from" languages.

![learning_flags_from_en](https://cloud.githubusercontent.com/assets/420926/16365435/3c55942e-3bce-11e6-97f6-6887825984e0.jpg)
![learning_flags_from_es](https://cloud.githubusercontent.com/assets/420926/16365436/3c55a11c-3bce-11e6-84e2-a44f25f62a3d.jpg)
![learning_flags_from_pt](https://cloud.githubusercontent.com/assets/420926/16365437/3c55e0be-3bce-11e6-8ddd-d13ed39c9567.jpg)

**Comment by arekolek** [comment]
In case you are not aware of my fork of this project, I have #[fixed this issue back in 2014](https://github.com/arekolek/DuolingoCourseSwitcher/commit/e8c8981c01c3383c72a8cc52b8e6e0fb1d450059).

**Comment by jimmysoda** [comment]
Thanks @arekolek - I will take a look at your fork.
